version: "3"

services:
  altagram-test:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile-test
    container_name: altagram-test
    env_file:
      - ./envs/test.env
    depends_on:
      - altagram-db-test

  altagram-db-test:
    image: postgres:13
    container_name: altagram-db-test
    environment:
      - POSTGRES_DB=altagram
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
