FROM python:3.9.1-slim-buster

WORKDIR /code

COPY requirements.txt /code/
COPY requirements-test.txt /code/
RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt

COPY . /code
RUN pip3 install -e .[test]
