FROM python:3.9.1-slim-buster

WORKDIR /code

RUN apt-get update && apt-get install -y postgresql-client

COPY requirements.txt /code/
RUN pip3 install  -r requirements.txt

COPY . /code
RUN pip3 install .

EXPOSE 5000
